# Generated by Django 3.0.7 on 2020-10-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201003_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='slug',
            new_name='movie_slug',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='body',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(blank=True, default=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(
                choices=[('1', 'G'), ('2', 'PG-13'), ('3', 'R')], default='PG-13', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rotten',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_now_amazon',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_now_amazon_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_now_netflix',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_now_netflix_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_now_youtube',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_now_youtube_link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
