# Generated by Django 3.0.7 on 2020-10-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201003_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watch_now_amazon',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_now_netflix',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_now_youtube',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
