# Generated by Django 3.0.7 on 2020-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201003_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_subtitle',
            field=models.CharField(blank=True, default='subtitle', max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(blank=True, default='title', max_length=100),
        ),
    ]
