# Generated by Django 3.0.7 on 2020-10-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20201003_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
