# Generated by Django 3.0.7 on 2020-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_thumbimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='posterimg',
            field=models.ImageField(blank=True, default='default3.jpeg', upload_to=''),
        ),
    ]
