# Generated by Django 3.0.7 on 2020-10-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20201012_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('1', 'G'), ('2', 'PG-13'), ('3', 'R'), ('4', 'PG'), ('5', 'TV-MA'), ('6', 'Not Rated')], max_length=1),
        ),
    ]
