# Generated by Django 3.0.7 on 2020-10-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gallery',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
